### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by jakob-fuchs** [concrete5-community-store/community_store_toolbar_buttons#1]
I extracted the package in the /packages directory but it doesn't appear in the dashboard. Folder name is 'community_store_toolbar_buttons'. Version 7.5.9

**Comment by Mesuva** [comment]
That's a weird one. I just tried downloading the package, renaming it to community_store_toolbar_buttons and visiting /index.php/dashboard/extend/install, it showed up and was installable (I'm using the exact same code on multiple sites)

The only thing I can think of is that you may need to check the permissions of the files themselves, perhaps they're not readable/executable by the webserver.

**Comment by jakob-fuchs** [comment]
Thanks for your reply. And yes, it was a permission problem, although I don't get it because other packages had no issues.
